version: "3"
services:
    chromium:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                ARCH: linux/amd64
        shm_size: "1gb"
        ports:
            - "9222:9222"
