name: build-web-builder-docker

on:
    workflow_dispatch:
        inputs:
        # no inputs

jobs:
    build-docker:
        name: build-docker

        # not using self-hosted-org because this needs to run docker in privileged mode (see setup-builder step)
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3
            - run: cat .env >> $GITHUB_ENV
            
            - name: setup-builder
              run: |
                  docker run --privileged --rm tonistiigi/binfmt --install all
                  echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USER}} --password-stdin
                  docker buildx create --name mybuilder --use
                  docker buildx ls

            - name: build-docker
              working-directory: ./
              run: |
                  echo "TAG=${{ steps.read-version.outputs.DOCKER_TAG }}"
                  docker buildx build -t "$DOCKER_HUB_REPO:$DOCKER_IMAGE_VERSION" --platform linux/amd64,linux/arm64 . --push

